CREATE TABLE IF NOT EXISTS USER (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT UNIQUE NOT NULL,PASSWORD TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS PROGRESS (ID INTEGER PRIMARY KEY AUTOINCREMENT,DEVICE_ID TEXT,DEVICE TEXT,PERCENTAGE REAL,PROGRESS TEXT,DOCUMENT TEXT,TIMESTAMP INTEGER,USER_ID INTEGER);
CREATE INDEX IF NOT EXISTS USER_NAME_INDEX ON USER (NAME);
CREATE INDEX IF NOT EXISTS DOCUMENT_ID_INDEX ON PROGRESS (USER_ID,DOCUMENT);