name = "koreader-sync-cf"
main = "build/worker/shim.mjs"
compatibility_date = "2025-09-16"

[build]
command = "cargo install -q worker-build --version 0.1.4 --force && worker-build --release"
# command = "worker-build --release"

[[d1_databases]]
binding = "koreader-sync"
database_name = "koreader-sync"
database_id = "cfc21b9f-4f65-464a-987c-bc8856935e31"

[observability.logs]
enabled = true
